#Test again with this version of Node.js
environment:
  matrix:
  # node.js
  - nodejs_version: "6"

#Install Scripts. (run after repo cloning)
install:
  # Get latest stable version of Node.js or io.js
  - ps Install-Product node $env:no
  # install modules
  - npm install

  #Post-install test Scripts
  test_script:
      #Output useful info for debugging
      - node --version
      - npm --version
      #run tests
      - npm test

# Dont actually build
  build: off

